[{'path': '/', 'name': 'SSOLoginState', 'value': '1502019262', 'domain': '.weibo.cn', 'httpOnly': False, 'secure': False}, {'expiry': 1533555262.590331, 'path': '/', 'name': 'SUHB', 'value': '0S7CGFNaIugT2s', 'domain': '.weibo.cn', 'httpOnly': False, 'secure': False}, {'expiry': 1533555262.589125, 'path': '/', 'name': 'SUB', 'value': '_2A250go7uDeRhGeBN61ER9y7MwzqIHXVXjBKmrDV6PUJbkdANLUnZkW10TWmGaNTw7n5RICIMpc7fVjKdug..', 'domain': '.weibo.cn', 'httpOnly': True, 'secure': False}, {'expiry': 1817379262.467507, 'path': '/', 'name': 'SCF', 'value': 'Aq5EAhGRUJ-GfsYHrWHFLAE8JZ9sgR5QRHhsxnWw1E7NqurHmuIA90aJ3APHbK15RZ5QCgE8h3kxg_J8PuYJiAI.', 'domain': '.weibo.cn', 'httpOnly': True, 'secure': False}, {'expiry': 1504611255.272421, 'path': '/', 'name': '_T_WM', 'value': '9c8b4c2589526f870fd89fd95d39dc23', 'domain': '.weibo.cn', 'httpOnly': True, 'secure': False}]
判断页面1成功 0失败  结果是=1
[<selenium.webdriver.remote.webelement.WebElement (session="7e692631bb0408e2b3ce3a82bdf21d0a", element="0.6968437119739148-1")>, <selenium.webdriver.remote.webelement.WebElement (session="7e692631bb0408e2b3ce3a82bdf21d0a", element="0.6968437119739148-2")>, <selenium.webdriver.remote.webelement.WebElement (session="7e692631bb0408e2b3ce3a82bdf21d0a", element="0.6968437119739148-3")>, <selenium.webdriver.remote.webelement.WebElement (session="7e692631bb0408e2b3ce3a82bdf21d0a", element="0.6968437119739148-4")>, <selenium.webdriver.remote.webelement.WebElement (session="7e692631bb0408e2b3ce3a82bdf21d0a", element="0.6968437119739148-5")>, <selenium.webdriver.remote.webelement.WebElement (session="7e692631bb0408e2b3ce3a82bdf21d0a", element="0.6968437119739148-6")>, <selenium.webdriver.remote.webelement.WebElement (session="7e692631bb0408e2b3ce3a82bdf21d0a", element="0.6968437119739148-7")>, <selenium.webdriver.remote.webelement.WebElement (session="7e692631bb0408e2b3ce3a82bdf21d0a", element="0.6968437119739148-8")>, <selenium.webdriver.remote.webelement.WebElement (session="7e692631bb0408e2b3ce3a82bdf21d0a", element="0.6968437119739148-9")>, <selenium.webdriver.remote.webelement.WebElement (session="7e692631bb0408e2b3ce3a82bdf21d0a", element="0.6968437119739148-10")>]
伦哥：好棒！第1次运行了
运行时间：2017-08-06 19:34:38
1
False
2
False
Traceback (most recent call last):
  File "my_repost.py", line 187, in <module>
    repost(driver1)
  File "my_repost.py", line 156, in repost
    browser.find_element_by_tag_name('body').send_keys(Keys.CONTROL + 'w')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 409, in find_element_by_tag_name
    return self.find_element(by=By.TAG_NAME, value=name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 791, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 254, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 464, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 487, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 707, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 693, in create_connection
    sock = socket(af, socktype, proto)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 134, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 23] Too many open files in system
