[{'expiry': 1504610317.656901, 'value': 'ae04855ae6b97114862fba080f001652', 'domain': '.weibo.cn', 'secure': False, 'httpOnly': True, 'name': '_T_WM', 'path': '/'}]
 (￣y▽￣)╭可能登录失败了手动登录一下吧
判断页面1成功 0失败  结果是=1
[<selenium.webdriver.remote.webelement.WebElement (session="cb8d16b3fae4fab04fcd08646612e921", element="0.6385481748189255-1")>, <selenium.webdriver.remote.webelement.WebElement (session="cb8d16b3fae4fab04fcd08646612e921", element="0.6385481748189255-2")>, <selenium.webdriver.remote.webelement.WebElement (session="cb8d16b3fae4fab04fcd08646612e921", element="0.6385481748189255-3")>, <selenium.webdriver.remote.webelement.WebElement (session="cb8d16b3fae4fab04fcd08646612e921", element="0.6385481748189255-4")>, <selenium.webdriver.remote.webelement.WebElement (session="cb8d16b3fae4fab04fcd08646612e921", element="0.6385481748189255-5")>, <selenium.webdriver.remote.webelement.WebElement (session="cb8d16b3fae4fab04fcd08646612e921", element="0.6385481748189255-6")>, <selenium.webdriver.remote.webelement.WebElement (session="cb8d16b3fae4fab04fcd08646612e921", element="0.6385481748189255-7")>, <selenium.webdriver.remote.webelement.WebElement (session="cb8d16b3fae4fab04fcd08646612e921", element="0.6385481748189255-8")>, <selenium.webdriver.remote.webelement.WebElement (session="cb8d16b3fae4fab04fcd08646612e921", element="0.6385481748189255-9")>, <selenium.webdriver.remote.webelement.WebElement (session="cb8d16b3fae4fab04fcd08646612e921", element="0.6385481748189255-10")>]
伦哥：好棒！第1次运行了
运行时间：2017-08-06 19:19:12
1
False
2
False
3
False
4
False
5
False
6
False
7
False
8
False
9
False
10
False
11
False
12
False
13
False
14
False
15
False
16
False
17
False
18
False
19
False
20
False
21
False
22
False
23
False
24
False
25
False
26
False
27
False
28
False
29
False
30
False
31
False
32
False
33
False
34
False
35
False
36
False
37
False
Traceback (most recent call last):
  File "my_repost.py", line 187, in <module>
    repost(driver1)
  File "my_repost.py", line 144, in repost
    browser.get(tweet_url)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 268, in get
    self.execute(Command.GET, {'url': url})
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=60.0.3112.90)
  (Driver info: chromedriver=2.31.488774 (7e15618d1bf16df8bf0ecf2914ed1964a387ba0b),platform=Mac OS X 10.12.6 x86_64)

